### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ogencoglu** [Nixtla/coreforecast#10]
What are the plans for docs?

**Comment by jmoralez** [comment]
Hey @ogencoglu, thanks for your interest in coreforecast. We're working on adding an API reference, however this library was meant to be used from other higher level interfaces like [mlforecast for lag transformations](https://nixtlaverse.nixtla.io/mlforecast/docs/how-to-guides/lag_transforms_guide.html#built-in-transformations-experimental).

Can you describe your use case so that we can see which type of documentation you would need?

**Comment by ogencoglu** [comment]
I think it would be fair to write 1-2 sentences (at least to README) what this library is about. That way people who encounter can assess if this library is for them or not. Is it for faster calculations or more accurate way of doing forecasts or what is it really?

You can for example write what you just said above:

> this library was meant to be used from other higher level interfaces like [mlforecast for lag transformations](https://nixtlaverse.nixtla.io/mlforecast/docs/how-to-guides/lag_transforms_guide.html#built-in-transformations-experimental).

and clarify why does `mlforecast` need a separate library in the first place.
